function [G] = ud_fields_solidbody(G) 

% setup user defined fields in main MALT structure
%
% DESCRIPTION:
%    setup user defined fields in main MALT structure
%
% INPUT:
%    G: MALT structure
%
% OUTPUT:
%    G: MALT structure
%
% EXAMPLE USAGE
%    G = init_struct(2000,3);
%
% Author(s):  
%    Geoff Cowles (University of Massachusetts Dartmouth)
%
% Revision history
%
% Usage:  Add fields using addfield, type "help addfield"
%
% G = addfield(G, ...
%  'varname','stage',...
%  'init_value',1,...
%  'output',true,...
%  'from_forcing','none',...
%  'longname','morphological stage',...
%  'units','-',...
%  'vtype','integer');
%==============================================================================


G = addfield(G, ...
 'varname','temp',...
 'init_value',0.0,...
 'output',true,...
 'from_forcing','temp',...
 'longname','temperature at particle',...
 'units','C',...
 'vtype','float');


return
